// Generated by scripts/generate-helper-adapter.mjs after forge build.
export const ENS_V2_ADAPTER = {
  "bytes": 7589,
  "hash": "0xa7031b687d56f3de503faed59fc263129fb8726e7ad6d1678a2de527733f3140",
  "ranges": [
    {
      "start": 175,
      "length": 32
    },
    {
      "start": 284,
      "length": 32
    },
    {
      "start": 381,
      "length": 32
    },
    {
      "start": 470,
      "length": 32
    },
    {
      "start": 528,
      "length": 32
    },
    {
      "start": 567,
      "length": 32
    },
    {
      "start": 686,
      "length": 32
    },
    {
      "start": 812,
      "length": 32
    },
    {
      "start": 850,
      "length": 32
    },
    {
      "start": 921,
      "length": 32
    },
    {
      "start": 1047,
      "length": 32
    },
    {
      "start": 1130,
      "length": 32
    },
    {
      "start": 1594,
      "length": 32
    },
    {
      "start": 1937,
      "length": 32
    },
    {
      "start": 2073,
      "length": 32
    },
    {
      "start": 2129,
      "length": 32
    },
    {
      "start": 2297,
      "length": 32
    },
    {
      "start": 2555,
      "length": 32
    },
    {
      "start": 2602,
      "length": 32
    },
    {
      "start": 2763,
      "length": 32
    },
    {
      "start": 3073,
      "length": 32
    },
    {
      "start": 3213,
      "length": 32
    },
    {
      "start": 3540,
      "length": 32
    },
    {
      "start": 4421,
      "length": 32
    },
    {
      "start": 4613,
      "length": 32
    },
    {
      "start": 4771,
      "length": 32
    },
    {
      "start": 4914,
      "length": 32
    },
    {
      "start": 4987,
      "length": 32
    },
    {
      "start": 5091,
      "length": 32
    },
    {
      "start": 5279,
      "length": 32
    }
  ]
} as const;
