/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/address": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get a deposit address
         * @description Activate deposit monitoring for an ENS name and return its deposit address, subname and supported funding chains.
         */
        post: operations["post_address"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status/{chainId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll a transaction
         * @description Retrieve renewal status for a USDC deposit transaction. The transaction is complete when every indexed deposit has a verified, finalized renewal.
         */
        get: operations["get_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Estimate a renewal
         * @description Estimate renewal duration and fees for an ENS name, funding chain and USDC amount. Quotes expire after 60 seconds and assume one processing flow with no existing balance at the deposit address.
         */
        post: operations["post_quote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/names/{name}/renewals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a name's renewals
         * @description Retrieve public renewal history and the recorded expiry for an ENS name. Renewals are ordered newest first. Complete indicates a verified, finalized renewal; processing indicates pending verification.
         */
        get: operations["get_name_renewals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
            requestId: string;
        };
        FundingChain: {
            /** @description Exact integer encoded as a decimal string. */
            chainId: string;
            name: string;
            tokenAddress: string;
            /** @description Minimum funding amount in six-decimal USDC units. */
            minimumAmount: string;
        };
        AddressResponse: {
            name: string;
            depositAddress: string;
            subname: string;
            subnameVerified: boolean;
            chains: components["schemas"]["FundingChain"][];
        };
        Renewal: {
            /** @description Exact integer encoded as a decimal string. */
            chainId: string;
            transactionHash: string;
            /** @description Exact integer encoded as a decimal string. */
            secondsAdded: string;
            /** Format: date-time */
            expiry: string | null;
        };
        DepositStatus: {
            name: string;
            depositAddress: string;
            logIndex: number | null;
            /** @description Deposited USDC, in six-decimal token units. */
            amount: string;
            /** @enum {string} */
            status: "pending" | "processing" | "complete" | "failed";
            reason: string | null;
            renewals: components["schemas"]["Renewal"][];
        };
        StatusResponse: {
            /** @description Exact integer encoded as a decimal string. */
            chainId: string;
            transactionHash: string;
            /** @enum {string} */
            status: "pending" | "processing" | "complete" | "failed";
            deposits: components["schemas"]["DepositStatus"][];
        };
        QuoteResponse: {
            name: string;
            /** @description Exact integer encoded as a decimal string. */
            chainId: string;
            /** @description Exact integer encoded as a decimal string. */
            amount: string;
            /** @description Exact integer encoded as a decimal string. */
            secondsAdded: string;
            /** @description Exact integer encoded as a decimal string. */
            amountApplied: string;
            /** @description Exact integer encoded as a decimal string. */
            renewalFee: string;
            /** @description Exact integer encoded as a decimal string. */
            bridgeFee: string;
            /** @description Exact integer encoded as a decimal string. */
            roundingRemainder: string;
            /** @description Exact integer encoded as a decimal string. */
            pricingBlock: string;
            /** Format: date-time */
            expiresAt: string;
            /** @constant */
            estimate: true;
        };
        HistoryItem: {
            /** Format: uuid */
            flowId: string;
            /** @description Exact integer encoded as a decimal string. */
            sourceChainId: string;
            /** @description Exact integer encoded as a decimal string. */
            chainId: string;
            transactionHash: string;
            /** @description Exact integer encoded as a decimal string. */
            secondsAdded: string | null;
            /** @description Exact integer encoded as a decimal string. */
            amountApplied: string | null;
            /** @description Exact integer encoded as a decimal string. */
            renewalFee: string | null;
            /** Format: date-time */
            expiry: string | null;
            /** @enum {string} */
            status: "processing" | "complete";
            /** Format: date-time */
            renewedAt: string;
        };
        HistoryResponse: {
            name: string;
            /** Format: date-time */
            currentExpiry: string | null;
            /** Format: date-time */
            expiryUpdatedAt: string | null;
            items: components["schemas"]["HistoryItem"][];
            nextCursor: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_address: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "example.eth"
                 *     }
                 */
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Address activated and ready for funding. */
            200: {
                headers: {
                    /** @description Seconds to wait before polling again when pending or temporarily unavailable. */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressResponse"];
                };
            };
            /** @description Invalid name, chain ID, transaction hash or request. */
            400: {
                headers: {
                    /** @description Seconds to wait before polling again when pending or temporarily unavailable. */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The ENS name cannot currently be renewed. */
            422: {
                headers: {
                    /** @description Seconds to wait before polling again when pending or temporarily unavailable. */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error. */
            500: {
                headers: {
                    /** @description Seconds to wait before polling again when pending or temporarily unavailable. */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Temporarily unavailable. Retry after the indicated delay. */
            503: {
                headers: {
                    /** @description Seconds to wait before polling again when pending or temporarily unavailable. */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    get_status: {
        parameters: {
            query: {
                /** @description The USDC deposit transaction hash returned by your wallet. */
                transactionHash: string;
            };
            header?: never;
            path: {
                /** @description Source EVM chain ID from the address response. */
                chainId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current progress. Poll pending or processing; stop at complete. */
            200: {
                headers: {
                    /** @description Seconds to wait before polling again when pending or temporarily unavailable. */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Invalid name, chain ID, transaction hash or request. */
            400: {
                headers: {
                    /** @description Seconds to wait before polling again when pending or temporarily unavailable. */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No matching deposit has been indexed. Retry the same URL. */
            404: {
                headers: {
                    /** @description Seconds to wait before polling again when pending or temporarily unavailable. */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error. */
            500: {
                headers: {
                    /** @description Seconds to wait before polling again when pending or temporarily unavailable. */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Temporarily unavailable. Retry after the indicated delay. */
            503: {
                headers: {
                    /** @description Seconds to wait before polling again when pending or temporarily unavailable. */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    post_quote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "example.eth",
                 *       "chainId": "84532",
                 *       "amount": "1000000"
                 *     }
                 */
                "application/json": {
                    name: string;
                    /** @description Exact integer encoded as a decimal string. */
                    chainId: string;
                    /** @description Exact integer encoded as a decimal string. */
                    amount: string;
                };
            };
        };
        responses: {
            /** @description Estimated renewal time and fee breakdown. */
            200: {
                headers: {
                    /** @description Seconds to wait before polling again when pending or temporarily unavailable. */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteResponse"];
                };
            };
            /** @description Invalid name, chain ID, transaction hash or request. */
            400: {
                headers: {
                    /** @description Seconds to wait before polling again when pending or temporarily unavailable. */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Name cannot currently renew, amount is below the minimum, or amount exceeds the single-flow quote limit. */
            422: {
                headers: {
                    /** @description Seconds to wait before polling again when pending or temporarily unavailable. */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error. */
            500: {
                headers: {
                    /** @description Seconds to wait before polling again when pending or temporarily unavailable. */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Temporarily unavailable. Retry after the indicated delay. */
            503: {
                headers: {
                    /** @description Seconds to wait before polling again when pending or temporarily unavailable. */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    get_name_renewals: {
        parameters: {
            query?: {
                /** @description Items per page; defaults to 20. */
                limit?: number;
                /** @description nextCursor from the previous page. Keep the same name. */
                cursor?: string;
            };
            header?: never;
            path: {
                /** @description ENS name, such as example.eth. */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Name expiry and renewal history. */
            200: {
                headers: {
                    /** @description Seconds to wait before polling again when pending or temporarily unavailable. */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Invalid name, chain ID, transaction hash or request. */
            400: {
                headers: {
                    /** @description Seconds to wait before polling again when pending or temporarily unavailable. */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description This name has not been activated. Get its deposit address first. */
            404: {
                headers: {
                    /** @description Seconds to wait before polling again when pending or temporarily unavailable. */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Server error. */
            500: {
                headers: {
                    /** @description Seconds to wait before polling again when pending or temporarily unavailable. */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Temporarily unavailable. Retry after the indicated delay. */
            503: {
                headers: {
                    /** @description Seconds to wait before polling again when pending or temporarily unavailable. */
                    "Retry-After"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
