import assert from 'node:assert/strict';
import {readFileSync, writeFileSync} from 'node:fs';
import {createPublicClient, http, encodeFunctionData, type PublicClient, type Hex} from 'viem';
import {buildPlan, bundle, HUB} from './model';
import {parseSession, json} from './storage';
import {recoverBurn, validateMessage, assertAttestedSource} from './canary';
const plan=buildPlan(parseSession(readFileSync('docs/deployments/2026-09-18/manifest.json','utf8')).config);
const arc=createPublicClient({transport:http('https://rpc.testnet.arc.network')}) as PublicClient;
const hub=createPublicClient({transport:http('https://ethereum-sepolia-rpc.publicnode.com')}) as PublicClient;
const reader=(id:number)=>{ assert([HUB,5042002].includes(id));return id===HUB?hub:arc; };
const record=await recoverBurn(plan,5042002,'vitalik','0x8ed795443a251a76d9f5ce774fe1fbfac172d2e0ab095dbcf17d1365eb5cf4ca',reader);
const iris=await fetch(`https://iris-api-sandbox.circle.com/v2/messages/26?transactionHash=${record.hash}`).then(r=>r.json());
assert.equal(iris.messages.length,1);const message=iris.messages[0];assert.equal(message.status,'complete');assert.equal(message.cctpVersion,2);
validateMessage(plan,5042002,'vitalik',message.message,true);
assertAttestedSource((record.evidence as {message:Hex}).message,message.message);
const data=encodeFunctionData({abi:bundle.contracts.NamepassL1Gateway.abi,functionName:'completeCCTP',args:[message.message,message.attestation]});
await hub.call({account:plan.config.owner,to:plan.deployments.NamepassL1Gateway.address,data});
const report={checkedAt:new Date().toISOString(),fingerprint:plan.fingerprint,record,attestationReady:true,claimSimulation:'passed',claimSubmitted:false};
writeFileSync('docs/deployments/2026-09-18/recovered-arc-burn.json',json(report)+'\n');
console.log('Missing burn verified; attestation ready; Sepolia claim simulation passed. No transaction sent.');
